-- WEFRYX Production: Supabase setup / migration
-- Выполни этот файл в Supabase -> SQL Editor.

create table if not exists public.portfolio (
  id bigint generated by default as identity primary key,
  title text not null,
  duration text default '',
  category text not null check (category in ('short','long')),
  video_path text not null,
  video_url text not null,
  published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);
alter table public.portfolio enable row level security;
drop policy if exists "public can read published portfolio" on public.portfolio;
create policy "public can read published portfolio" on public.portfolio for select using (published = true);


-- Администраторы. После создания пользователя в Authentication -> Users
-- добавь его UUID в эту таблицу. Только эти UUID получают права модерации.
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table public.admin_users enable row level security;
drop policy if exists "admins can read own admin record" on public.admin_users;
create policy "admins can read own admin record" on public.admin_users for select to authenticated using (user_id = auth.uid());

create or replace function public.is_wefryx_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.admin_users where user_id = auth.uid());
$$;

-- Портфолио: публично только опубликованное; изменение только администраторам.
drop policy if exists "authenticated can insert portfolio" on public.portfolio;
create policy "admins can insert portfolio" on public.portfolio for insert to authenticated with check (public.is_wefryx_admin());
drop policy if exists "authenticated can delete portfolio" on public.portfolio;
create policy "admins can delete portfolio" on public.portfolio for delete to authenticated using (public.is_wefryx_admin());
drop policy if exists "admins can update portfolio" on public.portfolio;
create policy "admins can update portfolio" on public.portfolio for update to authenticated using (public.is_wefryx_admin()) with check (public.is_wefryx_admin());

insert into storage.buckets (id,name,public) values ('portfolio-videos','portfolio-videos',true) on conflict (id) do nothing;
drop policy if exists "public read portfolio videos" on storage.objects;
create policy "public read portfolio videos" on storage.objects for select using (bucket_id='portfolio-videos');
drop policy if exists "authenticated upload portfolio videos" on storage.objects;
create policy "admins upload portfolio videos" on storage.objects for insert to authenticated with check (bucket_id='portfolio-videos' and public.is_wefryx_admin());
drop policy if exists "authenticated delete portfolio videos" on storage.objects;
create policy "admins delete portfolio videos" on storage.objects for delete to authenticated using (bucket_id='portfolio-videos' and public.is_wefryx_admin());

-- ОТЗЫВЫ
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  nickname text not null check (char_length(trim(nickname)) between 2 and 40),
  service_type text not null check (service_type in ('reels','long_video','commercial','motion')),
  rating integer not null check (rating between 1 and 5),
  review_text text not null check (char_length(trim(review_text)) between 5 and 1000),
  approved boolean not null default false,
  created_at timestamptz not null default now()
);
alter table public.reviews enable row level security;
-- Любой посетитель видит только одобренные отзывы.
drop policy if exists "public can read approved reviews" on public.reviews;
create policy "public can read approved reviews" on public.reviews for select using (approved = true);
-- Посетитель может только отправить новый отзыв и не может сразу его опубликовать.
drop policy if exists "public can submit reviews" on public.reviews;
create policy "public can submit reviews" on public.reviews for insert to anon, authenticated with check (approved = false);
-- Только админ может менять статус/удалять отзывы.
drop policy if exists "authenticated can manage reviews" on public.reviews;
create policy "admins can manage reviews" on public.reviews for update to authenticated using (public.is_wefryx_admin()) with check (public.is_wefryx_admin());
drop policy if exists "authenticated can delete reviews" on public.reviews;
create policy "admins can delete reviews" on public.reviews for delete to authenticated using (public.is_wefryx_admin());

-- ВАЖНО: если в базе уже есть тестовые/фиктивные отзывы, удалить их можно отдельно:
-- delete from public.reviews where nickname in ('Андрей В.','Екатерина С.','Михаил Т.');

-- После создания админского пользователя выполни:
-- insert into public.admin_users (user_id) values ('UUID_ПОЛЬЗОВАТЕЛЯ_ИЗ_AUTH_USERS');
